add new Android input method: fcitx5-android
rime/home pull request #1497
Opened 2024-03-14 02:24 UTC by gaboolic

安卓系统下的fcitx5-android也支持rime，希望把这个信息添加进去
配置文件和pc版本一样 完全兼容

2024-03-14 02:38 UTC, lotem commented
目前最新 release 的版本是 0.0.8
要不要等到軟件正式發佈再廣告？

2024-03-14 03:07 UTC, gaboolic commented
> 目前最新 release 的版本是 0.0.8 要不要等到軟件正式發佈再廣告？

这你决定吧，我只是一个普通用户
我从Google Play下载的，它上架到Google Play了有10k下载量
我使用下来 体验挺不错的

2024-03-14 03:08 UTC, gaboolic commented
如果认为增加fcitx5-android不合适，
可以只修改 fcitx5-rime查看[安裝方式](https://fcitx-im.org/wiki/Install_Fcitx_5/zh-cn) 这部分。它github仓库没写说明

2024-03-14 03:20 UTC, gaboolic commented
就我个人体验来说，fcitx5-android开箱即用，改rime配置也和pc端一样，易用性高
同文没有开箱即用，配置也多了皮肤的配置，上手难度高一点。不过同样可定制化程度高一点

2024-03-19 15:47 UTC, lotem requested changes
感謝更新。
文字格式希望做小幅修改。

2024-03-19 15:47 UTC, lotem commented on blog/source/download/index.md
> +*（第三方軟件）* [fcitx5-android](https://github.com/fcitx5-android/fcitx5-android) 〔[下載傳送門](https://github.com/fcitx5-android/fcitx5-android/releases)〕需要下載app本體及plugin.rime插件。是由 [fcitx5-android](https://gi
1.「是由……」接在「fcitx5-android」之後、「下載……」句之前比較通順。同文那一段也有同樣的語病。

2. 統一行文風格，在中文和西文之間加空格、在中文與鏈接之間加空格。

2024-03-20 02:48 UTC, gaboolic commented
已更新

2024-03-20 04:50 UTC, merged